from pathlib import Path
import html,json,os
ROOT=Path(__file__).parent
OUT=ROOT/'dist'
BASE_PATH=os.environ.get('SITE_BASE_PATH','').rstrip('/')
if BASE_PATH and (not BASE_PATH.startswith('/') or '..' in BASE_PATH):
 raise ValueError('SITE_BASE_PATH must be an absolute URL path prefix')
services=[
{'slug':'medical-map','name':'Medical Map','tag':'MEO・Googleマップ運用','short':'地域の検索から、来院のきっかけを。','desc':'医院情報の整備から投稿・口コミ返信、順位の確認まで。Googleマップの運用を継続的に支えます。','color':'','visual':'map'},
{'slug':'medical-map-plus','name':'Medical Map +','tag':'Googleマップ広告','short':'いま近くで探している人に、届ける。','desc':'地域と診療科に合わせて広告を配信。Googleマップで医院を探す患者さまとの接点をつくります。','color':'violet','visual':'mapad'},
{'slug':'medical-target-plus','name':'Medical Target +','tag':'ターゲティング広告','short':'比較・検討のタイミングを、逃さない。','desc':'診療圏や関心に合わせて配信対象を設計。医院を検討する方へ、貴院の特徴を届けます。','color':'navy','visual':'target'},
{'slug':'survey-plus','name':'アンケートプラス','tag':'患者アンケート・口コミ支援','short':'患者さまの声を、医院の力に。','desc':'来院後の声を集め、院内改善と口コミの接点へ。患者体験を知る仕組みを整えます。','color':'teal','visual':'survey'},
{'slug':'line-plus','name':'LINEプラス','tag':'LINE拡張ツール・運用支援','short':'来院した、その先もつながる。','desc':'タグ管理、配信の自動化、予約への案内まで。LINE拡張ツールで、患者さまとの接点を整えます。','color':'green','visual':'line'},
{'slug':'mynavi-clinic','name':'マイナビクリニックナビ','tag':'メディア掲載支援','short':'医院の魅力に、出会う場所を増やす。','desc':'地域・診療科で医院を探す方へ、紹介記事でアプローチ。掲載に向けた準備を支援します。','color':'sand','visual':'media'}]
def visual(s):
 return f'<div class="product-visual from-pdf"><img src="/assets/{s["slug"]}.webp" alt="{s["name"]} サービス資料" width="1440" height="810" loading="lazy"></div>'
def card(s):
 jp=' jp' if s['slug'] in ['survey-plus','line-plus','mynavi-clinic'] else ''
 return f'<a class="product-card reveal" href="/services/{s["slug"]}/">{visual(s)}<div class="card-body"><span class="product-tag">{s["tag"]}</span><h3 class="{jp}">{s["name"]}</h3><p>{s["desc"]}</p><div class="card-bottom">サービスを詳しく見る<span class="arrow-circle" aria-hidden="true">↗</span></div></div></a>'
def cta():
 return '<section class="contact-band"><div class="wrap contact-inner"><div><div class="eyebrow">LET’S TALK</div><h2>クリニックの次の一歩を、<br>ここから、一緒に。</h2><p>いまの課題や、これから実現したいことをお聞かせください。</p></div><a class="button" href="/contact/">サービスについて相談する<span class="arrow" aria-hidden="true">↗</span></a></div></section>'
def page(title,desc,body):
 icon='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="%230869ed"/><path d="M29 12a12 12 0 1 0 0 16" fill="none" stroke="white" stroke-width="5"/></svg>'
 return f'''<!doctype html><html lang="ja"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{html.escape(title)} | CRESTIX</title><meta name="description" content="{html.escape(desc)}"><meta name="theme-color" content="#ffffff"><meta property="og:title" content="{html.escape(title)} | CRESTIX"><meta property="og:description" content="{html.escape(desc)}"><meta property="og:type" content="website"><link rel="icon" type="image/svg+xml" href='data:image/svg+xml,{icon}'><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link rel="stylesheet" href="/style.css"><script defer src="/app.js"></script></head><body><a class="skip" href="#main">本文へ移動</a><header class="header"><div class="wrap header-inner"><a class="brand" href="/" aria-label="CRESTIX トップ"><img src="/assets/crestix-logo.png" alt="CRESTIX" width="152" height="42"><span class="brand-note">PRODUCTS &amp;<br>WEB CONSULTING</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation" aria-label="メニューを開く">☰</button><nav class="nav" id="navigation" aria-label="メインナビゲーション"><a href="/#products">プロダクト</a><a href="/consulting/">Webコンサルティング</a><a href="/#company">会社情報</a><a class="nav-contact" href="/contact/">お問い合わせ<span aria-hidden="true">↗</span></a></nav></div></header><main id="main">{body}</main><footer class="footer"><div class="wrap"><div class="footer-top"><div><a href="/" aria-label="CRESTIX トップ"><img src="/assets/crestix-logo.png" alt="CRESTIX" width="159" height="42" loading="lazy"></a><p class="footer-desc">クリニック向けプロダクト / Webコンサルティング</p></div><nav class="footer-links" aria-label="フッターナビゲーション"><a href="/#products">プロダクト</a><a href="/consulting/">Webコンサルティング</a><a href="/#company">会社情報</a><a href="/contact/">お問い合わせ</a></nav></div><div class="footer-bottom"><span>© 2026 Crestix Inc.</span><a href="https://www.crestix.jp/privacy.html" target="_blank" rel="noopener">プライバシーポリシー ↗</a><a href="#main">PAGE TOP ↑</a></div></div></footer></body></html>'''
def write(path,title,desc,body):
 p=OUT/path;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(page(title,desc,body).replace('href="/', f'href="{BASE_PATH}/').replace('src="/', f'src="{BASE_PATH}/'))
home='''<section class="hero"><img class="hero-art" src="/assets/hero.webp" alt="" width="1536" height="1024" fetchpriority="high"><div class="wrap hero-inner"><div class="eyebrow">CLINIC GROWTH PARTNER</div><h1>クリニックの成長を、<br><em>AIとデジタルで。</em></h1><p class="hero-copy">クリニック向けプロダクトと、Webコンサルティング。<br>AIを活かした開発・分析・制作で、<br>医院の集患と、患者さまとの接点づくりを支えます。</p><div class="hero-actions"><a class="button" href="#products">サービスを見る<span class="arrow" aria-hidden="true">↘</span></a><a class="text-link" href="/consulting/">私たちの支援について<span aria-hidden="true">↗</span></a></div></div><span class="hero-side">CRESTIX — PRODUCTS &amp; WEB CONSULTING</span></section><div class="hero-foot"><div class="wrap"><span class="hero-foot-label">FOR YOUR CLINIC</span><div class="pillars"><span><b>01</b>クリニック向けプロダクト</span><span><b>02</b>Webコンサルティング</span></div><a class="scroll-cue" href="#about"><i></i>SCROLL</a></div></div>
<section class="section intro" id="about"><div class="wrap"><div class="intro-grid"><div class="reveal"><div class="eyebrow">WHAT WE DO</div><h2>医療に向き合う時間を、<br>もっと。<br>成長の仕組みを、ともに。</h2></div><div class="intro-text reveal"><p>地域で見つけてもらい、医院の価値を知ってもらう。<br>そして、来院後も必要な情報を届けていく。</p><p>Crestixは、クリニックの患者接点をデジタルでつなぐ会社です。AIを活用した開発・制作と、医院ごとの課題に向き合うWebコンサルティング。プロダクトと戦略の両面から、続けられる成長の仕組みをつくります。</p></div></div><div class="two-pillars reveal"><a class="pillar" href="#products"><span class="pillar-num">01</span><div><h3>クリニック向けプロダクト</h3><p>集患・口コミ・患者コミュニケーションを支える。</p></div><span class="arrow-circle" aria-hidden="true">↘</span></a><a class="pillar" href="/consulting/"><span class="pillar-num">02</span><div><h3>Webコンサルティング</h3><p>課題の整理から、施策の実行・改善まで。</p></div><span class="arrow-circle" aria-hidden="true">↗</span></a></div></div></section>
<section class="section products" id="products"><div class="wrap"><div class="section-head reveal"><div><div class="eyebrow">PRODUCTS &amp; SERVICES</div><h2>必要な接点に、<br>適切なプロダクトを。</h2></div><p>地図検索、広告、口コミ、LINE、メディア。<br>医院の課題と患者さまの行動に合わせて、<br>サービスを組み合わせます。</p></div><div class="product-grid">'''+''.join(card(s) for s in services)+'''</div><p class="products-note">マイナビクリニックナビは株式会社マイナビが運営するメディアです。Crestixは掲載をご支援します。</p><div class="journey reveal"><p>患者さまとの接点を、<br>ひとつながりに。</p><div class="journey-line"><div class="journey-step"><small>DISCOVER</small>見つける</div><span aria-hidden="true">→</span><div class="journey-step"><small>CONSIDER</small>比較・検討する</div><span aria-hidden="true">→</span><div class="journey-step"><small>VISIT</small>来院する</div><span aria-hidden="true">→</span><div class="journey-step"><small>CONNECT</small>つながり続ける</div></div></div></div></section>
<section class="section consulting" id="consulting"><div class="wrap"><div class="consult-grid"><div class="reveal"><div class="eyebrow">WEB CONSULTING</div><h2>ツールの導入から、<br>成果に向かう運用へ。</h2><p>診療科、地域、医院の強み。<br>同じ施策でも、必要な進め方は医院ごとに異なります。<br>AIを情報整理・分析・制作に活かしながら、<br>専属コンサルタントが戦略設計から運用改善まで伴走。<br>貴院に合う次の一手を、一緒に考えます。</p><div class="consult-tags"><span>集患戦略</span><span>HP・LP制作</span><span>SEO・MEO</span><span>広告運用</span><span>予約導線の改善</span></div><a class="button light" href="/consulting/">Webコンサルティングを見る<span class="arrow" aria-hidden="true">↗</span></a></div><div class="consult-photo reveal"><img src="/assets/consulting.webp" alt="データを見ながらクリニックの施策を検討する様子" width="1536" height="1024" loading="lazy"></div></div><div class="steps"><div class="step reveal"><b>01 / UNDERSTAND</b><h3>現状を知る</h3><p>医院の目標・診療圏・患者導線から、課題を整理します。</p></div><div class="step reveal"><b>02 / DESIGN</b><h3>戦略を描く</h3><p>優先順位と指標を決め、必要な施策を選びます。</p></div><div class="step reveal"><b>03 / IMPLEMENT</b><h3>仕組みにする</h3><p>制作・設定・運用を通じて、計画を実行します。</p></div><div class="step reveal"><b>04 / IMPROVE</b><h3>改善を続ける</h3><p>反応を確認し、次の施策に活かします。</p></div></div></div></section>
<section class="section"><div class="wrap"><div class="section-head reveal"><div><div class="eyebrow">AI × HUMAN EXPERTISE</div><h2>AIを活かし、人が向き合う。</h2></div></div><div class="approach-list"><div class="approach-row reveal"><span>01</span><h3>AIを、開発の推進力に。</h3><p>開発プロセスにAIを取り入れ、プロダクトやWebの設計・実装・改善を進めます。医院が使いやすく、運用しやすい仕組みを形にします。</p></div><div class="approach-row reveal"><span>02</span><h3>分析から、次の一手へ。</h3><p>情報整理や分析、施策の検討にもAIを活用。医院の状況とデータを照らし合わせ、集患から予約までの改善につなげます。</p></div><div class="approach-row reveal"><span>03</span><h3>医院ごとの判断は、人が。</h3><p>担当者が内容を確認し、診療科・地域性・院内の体制を踏まえてご提案。AIの力と人の知見を組み合わせ、医院に合う運用を考え続けます。</p></div></div></div></section>
<section class="section company" id="company"><div class="wrap company-grid"><div class="reveal"><div class="eyebrow">COMPANY</div><h2>医療の可能性を、<br>デジタルでひらく。</h2><p class="company-copy">株式会社Crestixは、クリニックの集患と患者接点づくりを、プロダクトとWebコンサルティングで支援します。</p></div><dl class="reveal"><div><dt>会社名</dt><dd>株式会社Crestix（クレスティックス）</dd></div><div><dt>設立</dt><dd>2024年12月</dd></div><div><dt>所在地</dt><dd>〒101-0054<br>東京都千代田区神田錦町1丁目21-2<br>大手町モダンビルディング 4F</dd></div><div><dt>主な支援領域</dt><dd>クリニック向けデジタルマーケティング支援<br>プロダクト導入・運用 / Webコンサルティング</dd></div></dl></div></section>'''+cta()
write(Path('index.html'),'クリニックの成長を、AIとデジタルで。','CrestixはAIを活かした開発とWebコンサルティングで、クリニックの成長を支援。6つのサービスで集患から患者さまとの関係づくりまでを支えます。',home)
(OUT/'robots.txt').write_text('User-agent: *\nAllow: /\n')
if __name__=='__main__': print('Built home page')
