from pathlib import Path
from build import OUT, services, card, write, breadcrumb, cta


def build_corporate():
    home = '''
<section class="hero corporate-home-hero">
  <div class="line-field" aria-hidden="true"><svg viewBox="0 0 1600 700" preserveAspectRatio="none"><g class="line-wave wave-one"><path d="M -180 460 C 180 220, 500 150, 830 280 S 1290 350, 1780 150"/><path d="M -180 473 C 180 225, 500 162, 830 290 S 1290 340, 1780 168"/><path d="M -180 486 C 180 230, 500 174, 830 300 S 1290 330, 1780 186"/><path d="M -180 499 C 180 235, 500 186, 830 310 S 1290 320, 1780 204"/><path d="M -180 512 C 180 240, 500 198, 830 320 S 1290 310, 1780 222"/><path d="M -180 525 C 180 245, 500 210, 830 330 S 1290 300, 1780 240"/><path d="M -180 538 C 180 250, 500 222, 830 340 S 1290 290, 1780 258"/><path d="M -180 551 C 180 255, 500 234, 830 350 S 1290 280, 1780 276"/><path d="M -180 564 C 180 260, 500 246, 830 360 S 1290 270, 1780 294"/><path d="M -180 577 C 180 265, 500 258, 830 370 S 1290 260, 1780 312"/><path d="M -180 590 C 180 270, 500 270, 830 380 S 1290 250, 1780 330"/></g><g class="line-wave wave-two"><path d="M -180 460 C 180 220, 500 150, 830 280 S 1290 350, 1780 150"/><path d="M -180 473 C 180 225, 500 162, 830 290 S 1290 340, 1780 168"/><path d="M -180 486 C 180 230, 500 174, 830 300 S 1290 330, 1780 186"/><path d="M -180 499 C 180 235, 500 186, 830 310 S 1290 320, 1780 204"/><path d="M -180 512 C 180 240, 500 198, 830 320 S 1290 310, 1780 222"/><path d="M -180 525 C 180 245, 500 210, 830 330 S 1290 300, 1780 240"/><path d="M -180 538 C 180 250, 500 222, 830 340 S 1290 290, 1780 258"/></g></svg></div>
  <div class="wrap hero-inner">
    <div class="hero-heading"><p class="hero-kicker">CRESTIX / TECHNOLOGY FOR CLINICS</p><h1><span>TECHNOLOGY</span><span>FOR CLINIC</span><span>GROWTH.</span></h1></div>
    <div class="hero-message"><p class="hero-japanese">クリニックの成長を、<br>AIとデジタルで。</p><p class="hero-copy">クリニック向けプロダクトと、<br>Webコンサルティング。</p><a class="text-link hero-service-link" href="/services/medical-target-plus/"><span><small>MAIN SERVICE / ターゲティング広告</small>Medical Target +</span><span class="arrow-circle" aria-hidden="true">↗</span></a></div>
  </div>
  <div class="wrap hero-bottom"><a class="scroll-cue" href="#purpose"><span>SCROLL TO EXPLORE</span><i aria-hidden="true"></i></a><span>PRODUCTS / DEVELOPMENT / CONSULTING</span></div>
</section>
<section class="editorial-section purpose-section" id="purpose"><div class="wrap editorial-grid">
 <div class="section-title reveal"><span class="section-number">01</span><h2>Our<br>Purpose</h2><p>私たちが目指すこと</p></div>
 <div class="editorial-copy reveal"><h3>医院の可能性を、<br>もっと、その先へ。</h3><p>いい医療が、必要としている人に届くこと。<br>その出会いが、信頼へとつながっていくこと。</p><p>私たちは、クリニックの患者接点をデジタルでつなぐ会社です。日々の運用を支えるプロダクトと、医院ごとの課題に向き合うWebコンサルティング。その両面から、続けられる成長の仕組みをつくります。</p><a class="text-link" href="/company/">Crestixについて<span class="arrow-circle" aria-hidden="true">↗</span></a></div>
</div></section>
<section class="editorial-section business-section"><div class="wrap">
 <div class="editorial-grid business-heading"><div class="section-title reveal"><span class="section-number">02</span><h2>Our<br>Business</h2><p>事業紹介</p></div><div class="editorial-copy reveal"><h3>プロダクトと戦略で、<br>医院の次の一歩を。</h3><p>必要な仕組みを届けること。<br>その仕組みを、医院の成長につなげること。<br>Crestixは、その両方に取り組みます。</p></div></div>
 <div class="business-grid">
  <a class="business-card main-service-card reveal" href="/services/medical-target-plus/"><div class="business-card-copy"><div class="business-card-heading"><h3>Medical Target +</h3><span class="business-count">01</span></div><span class="business-label main-service-label">MAIN SERVICE / ターゲティング広告</span><p>医院を比較・検討する方へ、貴院の特徴を。<br>診療圏に合わせた配信設計から、バナー制作・運用改善まで支援します。</p></div><div class="business-art flagship-art"><img src="/assets/medical-target-plus.webp" alt="Medical Target + サービス資料" width="1440" height="810" loading="lazy"></div><span class="business-card-link">Medical Target + を詳しく見る<span class="arrow-circle" aria-hidden="true">↗</span></span></a>
  <a class="business-card reveal" href="/consulting/"><div class="business-card-copy"><div class="business-card-heading"><h3>Web Consulting</h3><span class="business-count">02</span></div><span class="business-label">Webコンサルティング</span><p>医院の課題を整理し、戦略から実行・改善へ。<br>専属コンサルタントが、次の一手を設計します。</p></div><div class="business-art"><img class="business-photo" src="/assets/consulting.webp" alt="データをもとに医院の施策を検討する様子" width="1536" height="1024" loading="lazy"></div><span class="business-card-link">Webコンサルティングへ<span class="arrow-circle" aria-hidden="true">↗</span></span></a>
 </div>
 <div class="business-more"><p>地図検索、口コミ、LINEなど、<br>医院の課題に合わせたサービスもご用意しています。</p><a class="text-link" href="/products/">すべてのプロダクトを見る<span class="arrow-circle" aria-hidden="true">↗</span></a></div>
</div></section>
<section class="editorial-section ai-section"><div class="wrap editorial-grid">
 <div class="section-title reveal"><span class="section-number">03</span><h2>AI &amp;<br>Human</h2><p><span class="title-part">AIを活かした開発と</span><wbr><span class="title-part">コンサルティング</span></p><div class="ai-wire" aria-hidden="true"><div class="wire-sphere"><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><span>DESIGN / DEVELOP / IMPROVE</span></div></div>
 <div class="editorial-copy reveal"><h3>AIの力と、<br>人の知見。その両方で。</h3><p>AIを、設計・実装・分析・制作のプロセスへ。<br>技術の力を活かしながら、担当者が内容を確認し、医院ごとの課題に向き合います。</p><p>何をつくるかだけでなく、どう役立てるかまで。<br>開発とWebコンサルティングをつなぎ、医院に合う仕組みを形にします。</p><a class="text-link" href="/development/">AIを活用した開発<span class="arrow-circle" aria-hidden="true">↗</span></a></div>
</div></section>
''' + cta()
    write(Path('index.html'), 'クリニックの成長を、AIとデジタルで。', 'クリニック向けプロダクトとWebコンサルティングのCrestix。AIを活かした開発・分析・制作で、医院の成長を支援します。', home)

    products = breadcrumb('プロダクト一覧') + '''
<section class="page-intro"><div class="wrap page-intro-grid"><div><div class="eyebrow">PRODUCTS &amp; SERVICES</div><h1>プロダクト一覧</h1><p class="page-lead">集患から、来院後のつながりまで。</p><p>主力のターゲティング広告「Medical Target +」を中心に、<br>医院の課題と患者さまの行動に合わせて、サービスを組み合わせます。</p></div><div class="service-count" aria-label="6つのサービス"><strong>06</strong><span>PRODUCTS &amp; SERVICES</span></div></div></section>
<section class="catalog-section"><div class="wrap">
<article class="featured-product"><a class="featured-product-image" href="/services/medical-target-plus/" aria-label="Medical Target + のサービス詳細"><img src="/assets/medical-target-plus.webp" alt="Medical Target + サービス資料" width="1440" height="810" loading="lazy"></a><div class="featured-product-copy"><div class="eyebrow">MAIN SERVICE / ターゲティング広告</div><h2>Medical Target +</h2><p class="featured-lead">比較・検討している方へ、<br>貴院の特徴を届ける。</p><p class="featured-description">診療圏や属性に合わせて配信対象を設計。バナー制作から広告配信、レポートをもとにした改善まで、まとめて支援します。</p><div class="featured-points"><span>診療圏・属性の設計</span><span>バナー制作</span><span>配信・改善</span></div><div class="featured-actions"><a class="button" href="/services/medical-target-plus/">サービスを詳しく見る<span class="arrow" aria-hidden="true">↗</span></a><a class="featured-contact" href="/contact/">導入について相談する<span aria-hidden="true">↗</span></a></div></div></article>
<div class="catalog-other-heading"><div class="eyebrow">MORE SERVICES</div><h2>医院の課題に合わせた、その他のサービス。</h2></div><div class="product-grid">''' + ''.join(card(s) for s in services if s['slug'] != 'medical-target-plus') + '''</div><p class="products-note">マイナビクリニックナビは株式会社マイナビが運営するメディアです。Crestixは掲載をご支援します。</p></div></section>
<section class="detail-section"><div class="wrap choice-guide"><div><div class="eyebrow">FIND YOUR NEXT STEP</div><h2>何から始めるかも、<br>一緒に考えます。</h2></div><div><p>医院の課題によって、必要な施策や優先順位は変わります。現状を整理するところから、導入後の運用までご相談いただけます。</p><a class="text-link" href="/consulting/">Webコンサルティングを見る<span aria-hidden="true">↗</span></a></div></div></section>
''' + cta()
    write(Path('products/index.html'), 'クリニック向けプロダクト一覧', '主力サービスMedical Target+をはじめ、Medical Map、Medical Map+、アンケートプラス、LINEプラス、マイナビクリニックナビ。クリニックの患者接点を支える6サービス。', products)

    development = breadcrumb('AIを活用した開発') + '''
<section class="development-hero"><div class="wrap development-hero-grid"><div><div class="eyebrow">AI &amp; DEVELOPMENT</div><h1>AIを、つくる力に。<br><span class="title-part">医院の課題を、</span><wbr><span class="title-part">仕組みに。</span></h1><p class="page-lead">AIを活用したプロダクト・Web開発</p><p>設計・実装・改善のプロセスにAIを取り入れ、担当者が内容を確認しながら形にする。医院が使いやすく、運用しやすい仕組みづくりに取り組みます。</p><a class="button" href="/contact/">開発について相談する<span class="arrow" aria-hidden="true">↗</span></a></div>
<div class="development-map" aria-label="AIと人の知見を組み合わせ、設計・実装・改善を進めます"><div class="dev-map-orbit" aria-hidden="true"></div><div class="dev-map-core"><strong>AI<span>×</span>HUMAN</strong><span>技術と、人の知見。</span></div><div class="dev-map-node node-design"><small>DESIGN</small>設計</div><div class="dev-map-node node-build"><small>DEVELOP</small>実装</div><div class="dev-map-node node-improve"><small>IMPROVE</small>改善</div><span class="dev-map-caption">BUILD FOR YOUR CLINIC</span></div></div></section>
<section class="detail-section"><div class="wrap"><div class="eyebrow">DEVELOPMENT SCOPE</div><h2>必要な体験を、必要な形で。</h2><div class="feature-list"><article class="feature reveal"><span class="num">01 / WEBSITE</span><h3>Webサイト・LP</h3><p>医院の特徴や診療内容を伝えるWebサイト、目的に合わせたLPを制作。情報設計から見せ方、問い合わせへの導線まで整えます。</p></article><article class="feature reveal"><span class="num">02 / PATIENT EXPERIENCE</span><h3>Web上の案内・導線</h3><p>診療案内、アクセス、予約方法など、患者さまが知りたい情報に迷わずたどり着ける体験を設計します。</p></article><article class="feature reveal"><span class="num">03 / CUSTOM DEVELOPMENT</span><h3>課題に合わせた個別開発</h3><p>既存のツールで対応できる範囲を整理し、医院の運用に合わせた仕組みを検討。必要な機能と開発範囲を明確にして進めます。</p></article></div></div></section>
<section class="detail-section soft"><div class="wrap"><div class="eyebrow">OUR PROCESS</div><h2>医院の目的から、開発を始める。</h2><div class="detail-flow"><div class="reveal"><b>STEP 01</b><h3>課題を整理する</h3><p>目的、利用する方、現在の運用を伺い、解決したいことを明確にします。</p></div><div class="reveal"><b>STEP 02</b><h3>仕様を設計する</h3><p>必要な機能、画面、情報の流れと、制作する範囲をすり合わせます。</p></div><div class="reveal"><b>STEP 03</b><h3>実装・確認する</h3><p>AIを開発に活用しながら、担当者が表示や動作、内容を確認します。</p></div><div class="reveal"><b>STEP 04</b><h3>運用につなげる</h3><p>医院の使い方に合わせて調整し、必要な改善や運用方法をご相談します。</p></div></div></div></section>
<section class="detail-section"><div class="wrap choice-guide"><div><div class="eyebrow">DEVELOPMENT × STRATEGY</div><h2>つくった先の、<br>活かし方まで。</h2></div><div><p>集患や予約までの患者導線を踏まえ、Webコンサルティングと開発をつなぎます。医院の目標に向かって、制作と運用を一緒に考えます。</p><a class="text-link" href="/consulting/">Webコンサルティングを見る<span aria-hidden="true">↗</span></a></div></div></section>
<section class="detail-section soft"><div class="wrap faq"><div class="eyebrow">FAQ</div><h2>開発のご相談について</h2><details><summary>つくりたいものが決まっていなくても相談できますか？</summary><p>はい。いま感じている課題や、実現したいことからお聞かせください。既存のプロダクトの活用も含めて、必要な仕組みを整理します。</p></details><details><summary>いま使っているサイトの改善も相談できますか？</summary><p>現在のサイトの構成・仕様・管理状況を確認し、対応できる範囲と進め方をご案内します。</p></details><details><summary>費用や期間はどのように決まりますか？</summary><p>必要な機能やページ数、制作範囲、既存システムの状況などを確認し、お見積もりと進行計画をご案内します。</p></details></div></section>
''' + cta()
    write(Path('development/index.html'), 'AIを活用した開発', 'AIを設計・実装・改善に活用するCrestixのプロダクト・Web開発。医院の課題に合わせ、Webサイトや必要な仕組みを形にします。', development)

    company = breadcrumb('会社情報') + '''
<section class="page-intro company-intro"><div class="wrap"><div class="eyebrow">COMPANY</div><h1>会社情報</h1><p class="page-lead">医療の可能性を、デジタルでひらく。</p></div></section>
<section class="section company-message"><div class="wrap company-message-grid"><div class="company-wordmark" aria-hidden="true">Crestix<span>TECHNOLOGY FOR CLINICS</span></div><div><div class="eyebrow">WHO WE ARE</div><h2>クリニックの隣で、<br>考え続ける会社。</h2><p>地域で見つけてもらい、医院の価値を知ってもらう。そして、来院後も必要な情報を届けていく。</p><p>株式会社Crestixは、クリニックの患者接点をデジタルでつなぐ会社です。日々の運用を支えるプロダクトと、医院ごとの課題に向き合うWebコンサルティング。その両面から、続けられる成長の仕組みをつくります。</p></div></div></section>
<section class="detail-section soft"><div class="wrap"><div class="eyebrow">OUR APPROACH</div><h2>技術を活かし、医院に向き合う。</h2><div class="feature-list"><article class="feature reveal"><span class="num">01</span><h3>クリニックを起点に。</h3><p>診療科や地域性、院内の体制を踏まえ、医院が届けたい価値と患者さまが知りたい情報をつなぎます。</p></article><article class="feature reveal"><span class="num">02</span><h3>AIと、人の知見を。</h3><p>AIを開発・分析・制作に活用。担当者が内容を確認し、医院ごとの事情に合う判断と提案につなげます。</p></article><article class="feature reveal"><span class="num">03</span><h3>運用を、ともに育てる。</h3><p>導入後のデータと現場の声をもとに改善。院内の負担に配慮しながら、継続できる運用を考えます。</p></article></div></div></section>
<section class="section company company-profile"><div class="wrap company-grid"><div><div class="eyebrow">COMPANY PROFILE</div><h2>会社概要</h2></div><dl><div><dt>会社名</dt><dd>株式会社Crestix（クレスティックス）</dd></div><div><dt>設立</dt><dd>2024年12月</dd></div><div><dt>所在地</dt><dd>〒101-0054<br>東京都千代田区神田錦町1丁目21-2<br>大手町モダンビルディング 4F</dd></div><div><dt>事業・支援領域</dt><dd>クリニック向けプロダクトの導入・運用<br>Webコンサルティング<br>AIを活用した開発・Web制作</dd></div><div><dt>お問い合わせ</dt><dd><a class="text-link" href="/contact/">お問い合わせ窓口<span aria-hidden="true">↗</span></a></dd></div></dl></div></section>
''' + cta()
    write(Path('company/index.html'), '会社情報', '株式会社Crestixの会社情報。クリニック向けプロダクト、Webコンサルティング、AIを活用した開発を通じて医院の成長を支援します。', company)
    (OUT / 'robots.txt').write_text('User-agent: *\nAllow: /\n')
    print('Built corporate home, products, development, and company pages')
